name             's2stories'
maintainer       'Will Fisher'
maintainer_email 'will@teknofire.net'
license          'all_rights'
description      'Installs/Configures s2stories'
long_description 'Installs/Configures s2stories'
version          '0.1.5'

depends 'chef-vault'
depends 'postgresql'
depends 'database'
depends 'rubies', '~> 0.1.0'
depends 'runit'
depends 'git'
depends 'user'
depends 'nodejs', '~> 2.4.0'
depends 'nginx'
depends 'certificate', '~> 1.0.0'
depends 'backup', '~> 1.3.0'
depends 'redisio'
depends 'teknobase'
